config:
  infra:imageTag: 5680977fa06a35080ea72d6bf24df4e09f7a1474
  infra:DATABASE_URL:
    secure: AAABAPuEW3wnZlWrTLXSSVOeOFqKxfCM6kJidNdsynPIdT4dzMx9zxLCGQ2XQIPiQy9zumcqB0E5bkEHaHSBv8qoDnrNRX3ijDbE0JznSVy7qEYXZzhBhbZB8LCljplOwOHLR/b9tV8F1OeKVjsqIZAY/rLA9OEhpAkKpTE9zzgRZ6W3eOFOmsh9yQvRQhaAIWqlXiPn/Z8UQ/DJA0Uni6vQ3Y5BPHW+nAzVGjGy6DlcrsHJ99kDasq4opM=
