name: infra
description: A minimal Kubernetes TypeScript Pulumi program
runtime:
  name: nodejs
  options:
    packagemanager: auto
config:
  pulumi:tags:
    value:
      pulumi:template: kubernetes-typescript
